apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orange-devops
  name: orange-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orange-devops
  template:
    metadata:
      labels:
        app: orange-devops
    spec:
      containers:
      - image: khalilshahin01/image-from-jenkins:v1
        imagePullPolicy: Always
        name: image-from-jenkins
