apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: OrangeDevOps
  name: OrangeDevOps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: OrangeDevOps
  template:
    metadata:
      labels:
        app: OrangeDevOps
    spec:
      containers:
      - image: khalilshahin01/image-from-jenkins:v1
        name: image-from-jenkins
