apiVersion: v1
kind: Service
metadata:
  labels:
    app: orange-devops
  name: orange-devops
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: orange-devops
  type: NodePort
status:
  loadBalancer: {}
